### ISSUE TITLE
update-engine version string is causing rollerd to panic

### ISSUE THREAD

**Issue by TerraTech** [coreroller/coreroller#18]
I will try to keep it terse, but if you need more detailed info I'll gladly pass it along.

I've been chasing down this problem as none of our CoreOS systems would ever get a valid update response back from CoreRoller and have finally pinned down the problem.

I captured the XML request from update-engine (CoreOS 1010.5.0) and it sends the following version string:
`version="1010.5.0+2016-05-27-1832"`

This causes CoreRoller to panic as viewed with debug logging turned on.  Trying to use 'update_engine_client -update' it just returned the standard error when no update was available even though behind the scenes a HTTP 500 error had occurred.

I crafted a modified XML response file and sent it via curl with the following version string and all other elements remaining the same.
`version="1010.5.0"`

With the date and ?revision? tag stripped off `+2016-05-27-1832`, CoreRoller then returned a proper "Update Required" type response.

I'm not sure of the history of `update-engine` but I guess somewhere along the way they added the extra information to the `version=` element.

**Comment by tegioz** [comment]
Hi @TerraTech,

Thanks for looking into this :)

I've been running a couple of tests that I'd like to share. 

A bit of context first:  the version that update-engine is now sending with the update requests looks a valid semver value according to the [spec](http://semver.org/#spec-item-10). CoreRoller does it best to deal always with valid semver values (versions aren't just strings anywhere), so as long as the version values provided are valid I'd expect them to be handled properly. CoreRoller uses a Postgresql extension called [pg-semver](https://github.com/theory/pg-semver) that helps a lot with data validation at the database level and some other niceties like ordering by semver fields, etc.

First thing I tested was to modify slightly one of the api tests so that it asked for an update using the value you provided that was causing issues. I got an error from Postgres that would have raised a 500 error as you described. I realised I had a very old version of the pg-semver extension so I updated it and tested again but it didn't work either (got a different error though, but related to the semver validation in Postgresql again).

```
pq: bad semver value '1010.5.0+2016-05-27-1832': pre-release (-) after metadata (+) at char 11
```

You can reproduce this issue out of CoreRoller quickly (if you do it in a different database you'll need to enable the extension for it though):

```
create table blabla (
	version semver
);

coreroller=# insert into blabla values ('1010.5.0');
INSERT 0 1

coreroller=# insert into blabla values ('1010.5.0+20160527');
INSERT 0 1

coreroller=# insert into blabla values ('1010.5.0+2016-05-27-1832');
ERROR:  bad semver value '1010.5.0+2016-05-27-1832': pre-release (-) after metadata (+) at char 13
LINE 1: insert into blabla values ('1010.5.0+2016-05-27-1832');
                                   ^
drop table blabla;
```

It looks like it doesn't like much those hyphens in the build metadata identifiers (they are used for pre-release info as well, so it can get confusing easily).

It would be great if you could confirm you are experiencing the same issue (please note that you may have an old version of the extension as well). If that's the case, I think the best approach would be to raise an issue in the pg-semver repository. Once it's fixed and if this is the only issue (there might be more in CoreRoller itself) it's just a matter of upgrading the extension in your Postgresql installation and restart it. I'll rebuild the Postgresql image in the Docker hub so that users using it can fix it just recreating the container.

Thanks.-

**Comment by TerraTech** [comment]
I ran your tests against `pg-semver-0.12.0` and got the same results.

Until pg-semver is fixed, I will most likely band-aid patch my CoreRoller tree to test for this semver pattern and reduce it down so that pg-semver won't choke on it.
(perl) psuedo:
```perl
if ($version =~ /^(\d+\.\d+\.\d+)\+\d+-/) {
  $version = $1;
}
```
As an aside, on the https://hub.docker.com/r/coreroller/postgres/ page, there is a minor typo:
s/sermver/semver/

Also, the screenshots area could be cleaned up by adding a clickable link to the github page "click here for screenshots" or something.

Thank you for being very responsive to this issue.  :)

**Comment by TerraTech** [comment]
This is now fixed upstream: pg-semver-0.13.0
https://github.com/theory/pg-semver/pull/20

**Comment by tegioz** [comment]
Thank you very much @TerraTech! I'll rebuild the images in the Docker hub.

**Comment by tegioz** [comment]
Hi @TerraTech,

I was testing the new version of the extension but I'm not sure if it's working fine. Please have a look below:

```
create table blabla (
    version semver
);

# insert into blabla values ('1010.5.0+2016-05-27-1832');
INSERT 0 1

# select * from blabla;
         version          
--------------------------
 1010.5.0-+016-05-27-1832
```

`1010.5.0-+016-05-27-1832` looks like it's not a valid semver value (there is an extra hyphen before the plus sign). Please note that the insertions are now allowed, but it may generate some internal problems in CoreRoller when it tries to read those versions to make decisions.

Sergio.-

**Comment by TerraTech** [comment]
I've pinged them in:  https://github.com/theory/pg-semver/issues/19#issuecomment-236416959
