### ISSUE TITLE
Issue with the CoreOS update.gz URL

### ISSUE THREAD

**Issue by xakraz** [coreroller/coreroller#31]
Hello,

I am facing an issue while trying to configure an update for my CoreOS clusters.

I have read https://github.com/coreroller/coreroller/issues/5 and sent a message on CoreOS User group here: https://groups.google.com/forum/#!topic/coreos-user/iZZqiyZSIls, but I was wondering if you had the solution to my problem ?

I don't know how to get the `update.gz` file ...

By the way, do you have a Slack, IRC or whatever way to communicate with each other ?

Thanks,

**Comment by tegioz** [comment]
Hi @xakraz 

I think they have already answered you :) 

Please note that CoreRoller has a mechanism to register CoreOS packages automatically. It runs periodically polling the official update servers and when it detects that new updates are available it creates new packages in CoreRoller and updates the corresponding channel. So you may not have to take care of this manually.

Creating them manually may be handy if your CoreRoller instance doesn't have access to the Internet or you are building your own images. If you don't expect to be using the automatic registration of CoreOS images you can disable it using the `-enable-syncer=false` argument in `rollerd`. Before it wasn't possible doing this through the UI, but that was fixed some time ago (#5). 
 
Cheers.-

**Comment by tegioz** [comment]
I forgot to mention, we don't use Slack or IRC to communicate to each other, sorry.

**Comment by xakraz** [comment]
Hello @tegioz , 

Thanks for your help, I will check out the CoreOS update auto sync feature.

It may be good to advertise it a bit more :D 
I searched in the readme and found the reference lost among the packages description in the backend.

I really like your project and will be glad to contribute. How can I help and were can I get started ?

**Comment by tegioz** [comment]
Hi @xakraz 

You are right, there are some features that may not be very well explained in the README file (some omitted completely!). It hasn't been properly updated in a while, but we'll do it soon to reflect this and some other changes as well.

About contributing to the project and related to the outdated README file (as it mentions that the project is under active development), the truth is that there isn't much work going on right now and nothing is planned for the short term. I would say it's been quite stable and used in some production sites for a long time with no major issues so our intention was to update a bit the docs and create a 1.0 release.

Any help regarding improving the docs, pointing out missing or unclear bits, etc, at this point would be highly appreciated. Testing it throughly and reporting bugs is always really helpful as well, specially if they are accompanied by details on how to reproduce it, a test case proving the issue or even a pull request with some code! :) 

If you were thinking of working in some new feature that might be interesting too. In that case please open an issue first to discuss the idea and its proposed design before writing any code, so that we can discuss if it's something that may be helpful to more people and fits the goals of the project.

Thanks!
