### ISSUE TITLE
Use as default the public CoreOS servers

### ISSUE THREAD

**Issue by rimusz** [coreroller/coreroller#32]
Can I use as default the public CoreOS servers with coreroller?
Or Am'I missing something here?
I want to run coreroller on Kubernetes.

**Comment by rimusz** [comment]
ok, got it running with persistent PG on Kubernetes.
Do I need to add CoreOS releases manually or it can be fetched automatically?

**Comment by tegioz** [comment]
Hi @rimusz 

Out of the box Coreroller polls the public CoreOS servers to create packages and update channels in your CR deployment as they become publicly available. So if `rollerd` has access to the Internet you'll see eventually new packages (pointing to the official image files) added to the CoreOS application. This functionality can be disabled if needed (i.e. you want to deploy your custom built images, etc).

Regarding your first question, your CoreOS servers should be configured to get updates from Coreroller instead of the public CoreOS update servers. That way updates can be properly controlled and tracked according to the configuration defined in your groups.

Cheers.-

**Comment by rimusz** [comment]
cool, thanks for your answer.
yes I noticed that beta channel already has pulled the latest image.
not sure why alpha/stable did not.
is any way I can force Coreroller to pull latets versions?

also it works just fine on kubernetes :) 

and thanks for the nice stuff.

**Comment by tegioz** [comment]
Coreroller (`syncer` helper) asks for updates to the public updates server as if it was any other CoreOS instance, but sometimes it looks like if updates were paused or not being offered at that particular moment. I'm not really sure why either, but I've noticed it sometimes specially during the weekends. 

There isn't any way to force CR to pull the latest versions, but you could create them manually using the UI if needed (they'll show up eventually anyway). I think polling happens every hour or so.

Cool, hope it's useful to you ;)

**Comment by rimusz** [comment]
ok, no worries then, will leave it running.
