### ISSUE TITLE
VMs dot not get assigned to the group

### ISSUE THREAD

**Issue by rimusz** [coreroller/coreroller#33]
I have created a group called `Workers` and have in my cloud-config:
```
  update:
    group: Workers
    server: http://coreroller.my.server/v1/update/
```
but still that VM ends up in `Stable` group which came with coreroller install

**Comment by tegioz** [comment]
When using groups other than `stable`, `beta` or `alpha` you have to use the group id instead of the name. It's mentioned in the README file but it looks optional instead of a requirement, I will try to make it a bit more clear.

https://github.com/coreroller/coreroller#new-machines

"In addition to the default stable, beta and alpha groups, you can also create and use custom groups to control the updates. In that case, you can use the group id you will find next to the group name in the dashboard instead of one of the official channels."

**Comment by rimusz** [comment]
gotcha, thanks
