### ISSUE TITLE
How can I update CoreOS channels?

### ISSUE THREAD

**Issue by mimmus** [coreroller/coreroller#35]
It is not clear for me,

**Comment by tegioz** [comment]
Hi @mimmus 

Out of the box Coreroller polls the public CoreOS update servers to create packages and update channels in your CR deployment as they become publicly available. So if rollerd has access to the Internet you'll see eventually new packages (pointing to the official image files) added to the CoreOS application in CR. This functionality can be disabled if needed (i.e. you want to deploy your custom built images, etc). You can also change the package an existing channel points to, create your own channels and point any group to it or even create your own groups.

Your CoreOS servers should be configured to get updates from Coreroller instead of the public CoreOS update servers (more info about this in the README file). That way updates can be properly controlled and tracked according to the rollout policy defined in your groups.

Cheers.-

**Comment by mimmus** [comment]
After one day, Coreroller show updates only fro Alpha and Beta channels, Stable is still at 766: what can I check?

Thanks again
