### ISSUE TITLE
Documentation for rollerd APIs

### ISSUE THREAD

**Issue by balavs7** [coreroller/coreroller#46]
We would like to automate the process of creating/updating applications/groups/channels/packages using API directly instead of using the UI. Is there some documentation on the APIs available?
Thanks, Bala

**Comment by tegioz** [comment]
Hi @balavs7 

You have two options as of today:

1. Use the internal Go API directly. This API wasn't thought to be used directly by external components but more as an internal core layer. Said that, it's probably the easiest way to build anything that talks to CoreRoller if you are planning to do it using Go. The main drawback is that it requires direct access to the database (bypassing the authentication layer). API package [GoDoc](https://godoc.org/github.com/coreroller/coreroller/backend/src/api) should help if you take this path.

2. Use the http API. The http API is just a wrapper around the Go API to expose a subset of its functionality over http (mainly to be consumed by the UI). Unfortunately it isn't documented so you'll have to check the code to see how it works. All you need should be in the `rollerd.go` and `controller.go` files in the `backend/src/cmd/rollerd` directory. Go documentation mentioned previously will be of help as well in this case.

At some point we may add a gRPC service to expose all API functionality nicely so that external tools can be written easily in any language (like the interesting `rollerctl` cli proposal by @xakraz in #44, which might be helpful to you as well).

Sergio.-

**Comment by samliddicott** [comment]
As an example, to get people going, you can post something like this make-package.json:

    {
     "filename": "FILENAME",
     "description": "DESCRIPTION",
     "url": "http://URL/",
     "version": "1.2.3-4",
     "type": 1,
     "size": "12345",
     "hash": "SHA1",
     "application_id": "e96281a6-d1af-4bde-9a0a-97b76e56dc57",
     "channels_blacklist": null,
     "coreos_action": {
      "sha256": "SHA256"
     }
    }

using curl, like this:

    < make-package.json curl -d@- --basic --user $USER:$PASSWORD \
      http://server:8000/api/apps/e96281a6-d1af-4bde-9a0a-97b76e56dc57/packages 

to create a coreos package on coreroller.

What you need to post for any particular action can be discovered by spying on the http post, using shift-ctrl-I on chrome, or other such tools -- even tcpdump
