### ISSUE TITLE
Question: Running multiple CoreRoller instances with one DB

### ISSUE THREAD

**Issue by johscheuer** [coreroller/coreroller#57]
Hi,

I wanted to ask if there are any known setups that use multiple CoreRoller instances with a single database? Are there any issues (race-conditions) with such a setup or should it work out-of-the-box? 

Thanks for your response!

**Comment by tegioz** [comment]
Hi @johscheuer 

Most of it will work just fine but there are some details you need to keep in mind when using multiple CoreRoller instances with a single database:

- The component in charge of keeping up to date the CoreOS application packages and channels (`syncer`) may be probably the only problematic one and some changes would be required to have multiple instances of it running at the same time. This problem can be mitigated by enabling this component in only one of the CR instances (it's behaviour is controlled by the `-enable-syncer` rollerd flag).

- If CoreRoller is going to host the payload of the packages (by default it doesn't and it's not required at all, just useful in some environments) you will probably need to setup a shared data volume and mount it in all instances. The one running the `syncer` will download the packages on it so that they can be served to clients requesting updates.

- Database migrations are embedded in the server binary and applied automatically when needed on start, so it's probably a good idea to rollout updates for CoreRoller one by one to let the first instance updated take care of them.

I'll keep thinking about it just in case I've missed something :)

Sergio.-
