### ISSUE TITLE
invalid input syntax for type inet: "unknown" ?

### ISSUE THREAD

**Issue by mimmus** [coreroller/coreroller#66]
Hi,
we are full of errors like this one:
```
ERROR:  invalid input syntax for type inet: "unknown" at character 87
STATEMENT:  WITH upd AS ( UPDATE "instance" SET "id" = '5295cb7cb9d641d1b5c9e826e4def76a', "ip" = 'unknown' WHERE (id = '5295cb7cb9d641d1b5c9e826e4def76a') RETURNING "id","ip"), ins AS ( INSERT INTO "instance"("id","ip") SELECT '5295cb7cb9d641d1b5c9e826e4def76a','unknown' WHERE NOT EXISTS (SELECT 1 FROM upd) RETURNING "id","ip") SELECT * FROM ins UNION ALL SELECT * FROM upd
```
and updates are not working correctly.

Any idea?

Thanks

**Comment by tegioz** [comment]
Hi @mimmus 

Were you able to find out what was going on?

The `ip` field in the instance table is of type `inet`, so the database is enforcing that the value we insert is a valid IP address. That's why it fails when the value `unknown` is used instead of a valid ip.

The ip used when registering an instance should be taken as described in the following piece of code. 

https://github.com/coreroller/coreroller/blob/cbf35fe7100322ce174e6266211232a5e8eede50/backend/src/cmd/rollerd/controller.go#L654-L673

**Comment by mimmus** [comment]
Solution disappeared from my brain :( Peraphs it was a proxy issue but not sure.

Sorry, you can close the issue
